import { Metadata } from "next";
import Link from "next/link";
import { ShieldCheck, Lock, EyeOff, ShieldAlert } from "lucide-react";
import { createStaticPageMetadata } from "@/lib/seo/metadata";

export const metadata: Metadata = createStaticPageMetadata({
  title: "Privacy Policy | Json Tools",
  description:
    "Read our privacy policy. Learn how Json Tools processes your JSON, SQL, JWT, and Base64 data 100% locally inside your browser with zero server uploads.",
  path: "/privacy",
});

export default function PrivacyPage() {
  return (
    <div className="max-w-3xl mx-auto space-y-8 py-6">
      <div className="border-b border-border-custom pb-6">
        <h1 className="text-3xl font-extrabold text-white flex items-center gap-2">
          <ShieldCheck className="text-emerald-500" size={32} />
          Privacy Policy
        </h1>
        <p className="mt-2 text-zinc-400 text-sm">Last updated: June 18, 2026</p>
      </div>

      <div className="rounded-lg border border-emerald-950 bg-emerald-950/10 p-5 flex gap-4 text-emerald-400 border-l-4 border-l-emerald-500">
        <Lock size={24} className="shrink-0 mt-0.5" />
        <div className="space-y-1">
          <h4 className="font-bold text-sm">Offline & Local-First Processing</h4>
          <p className="text-xs text-zinc-400 leading-relaxed">
            All tools provided on Json Tools operate entirely client-side. None of the text, code, JSON payloads, cryptographically generated UUIDs, or credentials you paste are uploaded, stored, or processed on our servers.
          </p>
        </div>
      </div>

      <section className="space-y-4 text-sm text-zinc-300 leading-relaxed">
        <h2 className="text-lg font-bold text-white">1. Data We Do Not Collect</h2>
        <p>
          Unlike traditional web applications, Json Tools is designed as a static client-side dashboard. We do not gather or transmit:
        </p>
        <ul className="list-disc list-inside pl-4 space-y-1 text-zinc-400">
          <li>JSON, SQL, JWT, Base64 strings, or regular expressions inputted into the editors.</li>
          <li>Output values generated by the conversions or formatters.</li>
          <li>Database credentials, tokens, or encryption keys.</li>
        </ul>
      </section>

      <section className="space-y-4 text-sm text-zinc-300 leading-relaxed">
        <h2 className="text-lg font-bold text-white">2. Browser Local Storage & Cookies</h2>
        <p>
          We do not use tracking cookies or gather personal behavioral profiles. The only storage utilized may be local browser cache or local storage, which stays confined on your device to persist UI theme selections (like dark mode state) and editor preferences.
        </p>
      </section>

      <section className="space-y-4 text-sm text-zinc-300 leading-relaxed">
        <h2 className="text-lg font-bold text-white">3. Third-Party CDNs</h2>
        <p>
          We fetch certain core assets, such as the Monaco Editor source code libraries, from public Content Delivery Networks (CDNs) like cdnjs or jsdelivr. CDNs may log standard browser header details (like IP address and User Agent) for security and CDN usage monitoring. No payload inputs are ever shared with these networks.
        </p>
      </section>

      <section className="space-y-4 text-sm text-zinc-300 leading-relaxed">
        <h2 className="text-lg font-bold text-white">4. Changes to This Policy</h2>
        <p>
          We may update this privacy statement occasionally to reflect modifications in local caching or tools design. The core policy remains unchanged: <strong>Your input data belongs to you and never leaves your computer.</strong>
        </p>
      </section>

      <div className="pt-6 border-t border-border-custom text-xs text-zinc-500">
        <p>
          If you have questions about our local-first implementation, feel free to review the source documentation or return to the{" "}
          <Link href="/" className="text-brand-blue hover:underline">
            Home Page
          </Link>.
        </p>
      </div>
    </div>
  );
}
